orbs:
  zappa: 'borb/zappa@0.1.0'
version: 2.1
workflows:
  deploy:
    jobs:
      - zappa/zappa-deploy:
          filters:
            branches:
              only: master
          python_version: '3.6'
          stage: prod

      - zappa/zappa-deploy:
          filters:
            branches:
              only: dev
          python_version: '3.6'
          stage: dev
