orbs:
  zappa: 'borb/zappa@0.1.0'
  pytest: thekevjames/pytest@0.0.60
version: 2.1
jobs:

workflows:
  deploy:
    jobs:
      - pytest/pytest:
          install_args: '-r requirements.txt'
      - zappa/zappa-deploy:
          requires:
            - pytest/pytest
          python_version: '3.6'
          stage: prod
      - zappa/zappa-deploy:
          filters:
            branches:
              only: dev
          python_version: '3.6'
          stage: dev
